/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { styled } from '@mui/material/styles'
import TarikaSideBar from './TarikaSideBar'
import TarikaTopBar from './TarikaTopBar'
import TarikaWorkOrderList from './TarikaWorkOrderList'
import TarikaFilters from './TarikaFilters'
import TarikaCenterList from './TarikaCenterList'
import useTarikaGlue from './useTarikaGlue'

const TarikaGlue1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: `1876px`,
  height: `1073px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
})

const LeftBar = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `345px`,
  height: `1073px`,
  margin: `0px`,
})

const TarikaSideBar1 = styled(TarikaSideBar)(({ theme }) => ({
  width: `345px`,
  height: `1073px`,
  margin: `0px`,
}))

const RightBar = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1531px`,
  height: `1073px`,
  margin: `0px`,
})

const TarikaTopBar1 = styled(TarikaTopBar)(({ theme }) => ({
  margin: `0px`,
}))

const TarikaWorkOrderList1 = styled(TarikaWorkOrderList)(({ theme }) => ({
  height: `67px`,
  width: `1531px`,
  margin: `0px`,
}))

const TarikaFilters1 = styled(TarikaFilters)(({ theme }) => ({
  height: `54px`,
  width: `1531px`,
  margin: `0px`,
}))

const TarikaCenterList1 = styled(TarikaCenterList)(({ theme }) => ({
  height: `876px`,
  width: `1521px`,
  margin: `0px`,
}))

function TarikaGlue(props) {
  const { data } = useTarikaGlue()
  return (
    <TarikaGlue1 className={props.className}>
      <LeftBar>
        <TarikaSideBar1 />
      </LeftBar>
      <RightBar>
        <TarikaTopBar1 />
        <TarikaWorkOrderList1 />
        <TarikaFilters1 />
        <TarikaCenterList1 data={data} />
      </RightBar>
    </TarikaGlue1>
  )
}

export default TarikaGlue
