/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';

 
const TarikaWorkOrderList1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const WorkOrderListText = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `27px`,  
  width: `1521px`,  
  margin: `0px`,  
});
  
const WorkOrderList = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(38, 38, 38, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `2px`,  
  top: `0px`,  
});
  
const Line74 = styled("div")({  
  border: `0.5px solid rgba(119, 119, 119, 1)`,  
  width: `1521px`,  
  height: `0px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `27px`,  
});
 
function TarikaWorkOrderList(props) {
  return (
    <TarikaWorkOrderList1 className={props.className} >
      <WorkOrderListText >
        <WorkOrderList >
          {`Work Order List`}
            </WorkOrderList>
        <Line74 >
        </Line74>
      </WorkOrderListText>
    </TarikaWorkOrderList1>
  );
}

export default TarikaWorkOrderList;
