/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import Path1624Image from './assets/images/tarikasidebar_Path_1624.png';
import Path1625Image from './assets/images/tarikasidebar_Path_1625.png';
import Ellipse35Image from './assets/images/tarikasidebar_Ellipse_35.png';
import Path1626Image from './assets/images/tarikasidebar_Path_1626.png';
import Path1627Image from './assets/images/tarikasidebar_Path_1627.png';
import Path1628Image from './assets/images/tarikasidebar_Path_1628.png';
import Path2176Image from './assets/images/tarikasidebar_Path_2176.png';
import Path2177Image from './assets/images/tarikasidebar_Path_2177.png';
import Q1608951TicketIconImage from './assets/images/tarikasidebar__1608951_ticket_icon.png';
import Path1911Image from './assets/images/tarikasidebar_Path_1911.png';
import Path1912Image from './assets/images/tarikasidebar_Path_1912.png';
import Path1913Image from './assets/images/tarikasidebar_Path_1913.png';
import Path1914Image from './assets/images/tarikasidebar_Path_1914.png';
import Path1915Image from './assets/images/tarikasidebar_Path_1915.png';
import Path1916Image from './assets/images/tarikasidebar_Path_1916.png';
import Path1917Image from './assets/images/tarikasidebar_Path_1917.png';
import Path1918Image from './assets/images/tarikasidebar_Path_1918.png';
import Path1919Image from './assets/images/tarikasidebar_Path_1919.png';
import Path1920Image from './assets/images/tarikasidebar_Path_1920.png';
import Ellipse13Image from './assets/images/tarikasidebar_Ellipse_13.png';
import Path2008Image from './assets/images/tarikasidebar_Path_2008.png';
import BackgroundImage from './assets/images/tarikasidebar_background.png';
import IconAwesomePowerOffImage from './assets/images/tarikasidebar_Icon_awesome_power_off.png';
import Path2Image from './assets/images/tarikasidebar_Path_2.png';
import Path3Image from './assets/images/tarikasidebar_Path_3.png';
import Path4Image from './assets/images/tarikasidebar_Path_4.png';
import EbimsLogoWhite1Image from './assets/images/tarikasidebar_ebims_logo_white_1.png';
import { styled } from '@mui/material/styles';
import useTarikaSideBar from './useTarikaSideBar';
 
const TarikaSideBar1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const SideBar = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `345px`,  
  height: `1080px`,  
  margin: `0px`,  
});
  
const MainLeftBg = styled("div")({  
  backgroundColor: `rgba(35, 46, 56, 1)`,  
  width: `345px`,  
  height: `1080px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const FooterText = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `235px`,  
  height: `29px`,  
  left: `60px`,  
  top: `1016px`,  
});
  
const ProductByTarikaTechn = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `29px`,  
});
  
const ClientPortalVersionV = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const LeftMenu = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `277px`,  
  height: `247.08px`,  
  left: `28px`,  
  top: `193px`,  
});
  
const Rectangle17010 = styled("div")({  
  backgroundColor: `rgba(26, 94, 255, 1)`,  
  borderRadius: `8px`,  
  width: `277px`,  
  height: `47px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const WorkOrders = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `125px`,  
  height: `26px`,  
  left: `33px`,  
  top: `11px`,  
  cursor: `pointer`,  
});
  
const WorkOrders1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `41px`,  
  top: `5px`,  
});
  
const Icon1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `26px`,  
  height: `26px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path1624 = styled("img")({  
  height: `6.5px`,  
  width: `26px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path1625 = styled("img")({  
  height: `17.34px`,  
  width: `17.34px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `9px`,  
});
  
const Ellipse35 = styled("img")({  
  height: `6.5px`,  
  width: `6.5px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `19px`,  
});
  
const Path1626 = styled("img")({  
  height: `1.63px`,  
  width: `6.5px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `12px`,  
});
  
const Path1627 = styled("img")({  
  height: `1.63px`,  
  width: `6.47px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `9px`,  
});
  
const Path1628 = styled("img")({  
  height: `1.63px`,  
  width: `6.44px`,  
  position: `absolute`,  
  left: `20px`,  
  top: `15px`,  
});
  
const Invoices = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `93.73px`,  
  height: `25.47px`,  
  left: `33px`,  
  top: `81px`,  
  cursor: `pointer`,  
});
  
const Invoices1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `40px`,  
  top: `4px`,  
});
  
const InvoiceIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `25.47px`,  
  height: `25.47px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path2176 = styled("img")({  
  height: `25.47px`,  
  width: `19.53px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path2177 = styled("img")({  
  height: `13.58px`,  
  width: `13.58px`,  
  position: `absolute`,  
  left: `12px`,  
  top: `12px`,  
});
  
const Tickets = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `89.83px`,  
  height: `29.67px`,  
  left: `30px`,  
  top: `150px`,  
  cursor: `pointer`,  
});
  
const Tickets1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `44px`,  
  top: `6px`,  
});
  
const Q1608951TicketIcon = styled("img")({  
  height: `29.67px`,  
  width: `29.67px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Projects = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `92.74px`,  
  height: `23.08px`,  
  left: `33px`,  
  top: `224px`,  
  cursor: `pointer`,  
});
  
const Projects1 = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `40px`,  
  top: `3px`,  
});
  
const EditIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `23.48px`,  
  height: `23.08px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Path1911 = styled("img")({  
  height: `18.45px`,  
  width: `6.11px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `2px`,  
});
  
const Path1912 = styled("img")({  
  height: `6.06px`,  
  width: `3.5px`,  
  position: `absolute`,  
  left: `17px`,  
  top: `16px`,  
});
  
const Path1913 = styled("img")({  
  height: `21.8px`,  
  width: `17.64px`,  
  position: `absolute`,  
  left: `3px`,  
  top: `0px`,  
});
  
const Path1914 = styled("img")({  
  height: `10.22px`,  
  width: `6.07px`,  
  position: `absolute`,  
  left: `16px`,  
  top: `11px`,  
});
  
const Path1915 = styled("img")({  
  height: `5.28px`,  
  width: `5.28px`,  
  position: `absolute`,  
  left: `3px`,  
  top: `1px`,  
});
  
const Path1916 = styled("img")({  
  height: `2.25px`,  
  width: `2.56px`,  
  position: `absolute`,  
  left: `21px`,  
  top: `7px`,  
});
  
const Path1917 = styled("img")({  
  height: `1.21px`,  
  width: `1.01px`,  
  position: `absolute`,  
  left: `13px`,  
  top: `22px`,  
});
  
const Path1918 = styled("img")({  
  height: `2.52px`,  
  width: `0.84px`,  
  position: `absolute`,  
  left: `21px`,  
  top: `9px`,  
});
  
const Path1919 = styled("img")({  
  height: `9.8px`,  
  width: `6.39px`,  
  position: `absolute`,  
  left: `14px`,  
  top: `10px`,  
});
  
const Path1920 = styled("img")({  
  height: `1.59px`,  
  width: `2.01px`,  
  position: `absolute`,  
  left: `14px`,  
  top: `20px`,  
});
  
const UserProfileArea = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `173.84px`,  
  height: `55.67px`,  
  left: `58px`,  
  top: `106px`,  
});
  
const UserText = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `94px`,  
  height: `48px`,  
  left: `80px`,  
  top: `5px`,  
});
  
const JohnStone = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Designation = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `29px`,  
});
  
const UserIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `55.67px`,  
  height: `55.67px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Ellipse13 = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  position: `absolute`,  
  left: `21px`,  
  top: `13px`,  
});
  
const Path2008 = styled("img")({  
  height: `55.67px`,  
  width: `55.67px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const LogoutButton = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `344px`,  
  height: `39px`,  
  left: `1px`,  
  top: `943px`,  
});
  
const Background = styled("img")({  
  height: `39px`,  
  width: `344px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group7165 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `83.7px`,  
  height: `19px`,  
  left: `61px`,  
  top: `10px`,  
});
  
const Logout = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `700`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `37px`,  
  top: `0px`,  
  cursor: `pointer`,  
});
  
const IconAwesomePowerOff = styled("img")({  
  height: `18.99px`,  
  width: `18.7px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const UpperArea = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `344px`,  
  height: `76px`,  
  left: `1px`,  
  top: `0px`,  
});
  
const Rectangle17012 = styled("div")({  
  backgroundColor: `rgba(35, 46, 56, 1)`,  
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,  
  width: `344px`,  
  height: `76px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const HamburgerIcon = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `21.99px`,  
  height: `18px`,  
  left: `292px`,  
  top: `28px`,  
});
  
const Path2 = styled("img")({  
  height: `3px`,  
  width: `21.99px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `15px`,  
});
  
const Path3 = styled("img")({  
  height: `3px`,  
  width: `21.99px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `7px`,  
});
  
const Path4 = styled("img")({  
  height: `3px`,  
  width: `21.99px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const EbimsLogoWhite1 = styled("img")({  
  height: `53px`,  
  width: `93px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `57px`,  
  top: `12px`,  
});
 
function TarikaSideBar(props) {
  const {fns} = useTarikaSideBar();
  return (
    <TarikaSideBar1 className={props.className} >
      <SideBar >
        <MainLeftBg >
        </MainLeftBg>
        <FooterText >
          <ProductByTarikaTechn >
            {`Product by: Tarika Technologies TM`}
              </ProductByTarikaTechn>
          <ClientPortalVersionV >
            {`Client Portal Version: v2.0`}
              </ClientPortalVersionV>
        </FooterText>
        <LeftMenu >
          <Rectangle17010 >
          </Rectangle17010>
          <WorkOrders onClick={() => fns.handleNavigation('/workorders')} >
            <WorkOrders1 >
              {`Work Orders`}
                </WorkOrders1>
            <Icon1 >
              <Path1624  src={Path1624Image} alt={"Path 1624"}/>
              <Path1625  src={Path1625Image} alt={"Path 1625"}/>
              <Ellipse35  src={Ellipse35Image} alt={"Ellipse 35"}/>
              <Path1626  src={Path1626Image} alt={"Path 1626"}/>
              <Path1627  src={Path1627Image} alt={"Path 1627"}/>
              <Path1628  src={Path1628Image} alt={"Path 1628"}/>
            </Icon1>
          </WorkOrders>
          <Invoices onClick={() => fns.handleNavigation('/invoices')} >
            <Invoices1 >
              {`Invoices`}
                </Invoices1>
            <InvoiceIcon >
              <Path2176  src={Path2176Image} alt={"Path 2176"}/>
              <Path2177  src={Path2177Image} alt={"Path 2177"}/>
            </InvoiceIcon>
          </Invoices>
          <Tickets onClick={() => fns.handleNavigation('/tickets')} >
            <Tickets1 >
              {`Tickets`}
                </Tickets1>
            <Q1608951TicketIcon  src={Q1608951TicketIconImage} alt={"1608951_ticket_icon"}/>
          </Tickets>
          <Projects onClick={() => fns.handleNavigation('/projects')} >
            <Projects1 >
              {`Projects`}
                </Projects1>
            <EditIcon >
              <Path1911  src={Path1911Image} alt={"Path 1911"}/>
              <Path1912  src={Path1912Image} alt={"Path 1912"}/>
              <Path1913  src={Path1913Image} alt={"Path 1913"}/>
              <Path1914  src={Path1914Image} alt={"Path 1914"}/>
              <Path1915  src={Path1915Image} alt={"Path 1915"}/>
              <Path1916  src={Path1916Image} alt={"Path 1916"}/>
              <Path1917  src={Path1917Image} alt={"Path 1917"}/>
              <Path1918  src={Path1918Image} alt={"Path 1918"}/>
              <Path1919  src={Path1919Image} alt={"Path 1919"}/>
              <Path1920  src={Path1920Image} alt={"Path 1920"}/>
            </EditIcon>
          </Projects>
        </LeftMenu>
        <UserProfileArea >
          <UserText >
            <JohnStone >
              {`John Stone`}
                </JohnStone>
            <Designation >
              {`Designation`}
                </Designation>
          </UserText>
          <UserIcon >
            <Ellipse13  src={Ellipse13Image} alt={"Ellipse 13"}/>
            <Path2008  src={Path2008Image} alt={"Path 2008"}/>
          </UserIcon>
        </UserProfileArea>
        <LogoutButton >
          <Background  src={BackgroundImage} alt={"background"}/>
          <Group7165 >
            <Logout onClick={()=>fns.handleNavigation('/')} >
              {`Logout`}
                </Logout>
            <IconAwesomePowerOff  src={IconAwesomePowerOffImage} alt={"Icon awesome-power-off"}/>
          </Group7165>
        </LogoutButton>
        <UpperArea >
          <Rectangle17012 >
          </Rectangle17012>
          <HamburgerIcon >
            <Path2  src={Path2Image} alt={"Path 2"}/>
            <Path3  src={Path3Image} alt={"Path 3"}/>
            <Path4  src={Path4Image} alt={"Path 4"}/>
          </HamburgerIcon>
          <EbimsLogoWhite1  src={EbimsLogoWhite1Image} alt={"ebims-logo-white 1"}/>
        </UpperArea>
      </SideBar>
    </TarikaSideBar1>
  );
}

export default TarikaSideBar;
