/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import VectorImage from './assets/images/tarikafilters_Vector_3.png';
import Vector1Image from './assets/images/tarikafilters_Vector_2.png';
import CalendarImage from './assets/images/tarikafilters_Calendar.png';
import Vector2Image from './assets/images/tarikafilters_Vector_1.png';
import ResetButtonImage from './assets/images/tarikafilters_Reset_Button.png';
import Rectangle17157Image from './assets/images/tarikafilters_Rectangle_17157.png';
import Vector3Image from './assets/images/tarikafilters_Vector.png';
import { styled } from '@mui/material/styles';

 
const TarikaFilters1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 5px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const TopFiltersAnotherOpt = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1508.31px`,  
  margin: `0px`,  
});
  
const Frame2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1093px`,  
  height: `25px`,  
  margin: `0px`,  
});
  
const Filters = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 5px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Frame7 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 5px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const StatusAll = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `61.1px`,  
  margin: `0px`,  
});
  
const Vector = styled("img")({  
  height: `7px`,  
  width: `10.02px`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Frame6 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 5px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 5px`,  
});
  
const SearchByAll = styled("div")({  
  textAlign: `right`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `83.14px`,  
  margin: `0px`,  
});
  
const Vector1 = styled("img")({  
  height: `7px`,  
  width: `10.02px`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Calendar = styled("img")({  
  height: `33px`,  
  width: `41px`,  
  margin: `0px 0px 0px 5px`,  
});
  
const SearchBar = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `579px`,  
  height: `33px`,  
  margin: `0px 0px 0px 5px`,  
});
  
const Rectangle17155 = styled("div")({  
  border: `0.5px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `5px`,  
  width: `579px`,  
  height: `33px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SearchWoTitle = styled("div")({  
  textAlign: `right`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(112, 112, 112, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `20px`,  
  top: `17px`,  
});
  
const Group7281 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `23px`,  
  height: `23px`,  
  left: `547px`,  
  top: `6px`,  
});
  
const Rectangle17156 = styled("div")({  
  backgroundColor: `rgba(53, 53, 53, 1)`,  
  borderRadius: `3px`,  
  width: `23px`,  
  height: `23px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector2 = styled("img")({  
  height: `12.52px`,  
  width: `12.52px`,  
  position: `absolute`,  
  left: `5px`,  
  top: `5px`,  
});
  
const ResetButton = styled("img")({  
  height: `33px`,  
  width: `41px`,  
  margin: `0px 0px 0px 5px`,  
});
  
const Frame1 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `334px`,  
  height: `29px`,  
  margin: `0px 0px 0px 81px`,  
});
  
const Frame3 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 20px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Frame4 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Rectangle17157 = styled("img")({  
  height: `16px`,  
  width: `19.11px`,  
  margin: `0px`,  
});
  
const GroupingByMonths = styled("div")({  
  textAlign: `right`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `154.57px`,  
  margin: `0px`,  
});
  
const Frame5 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 10px`,  
});
  
const Legend = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `73.27px`,  
  margin: `0px`,  
});
  
const Vector3 = styled("img")({  
  height: `7px`,  
  width: `18.51px`,  
  margin: `0px`,  
});
 
function TarikaFilters(props) {
  return (
    <TarikaFilters1 className={props.className} >
      <TopFiltersAnotherOpt >
        <Frame2 >
          <Filters >
            <Frame7 >
              <StatusAll >
                {`Status: All`}
                  </StatusAll>
              <Vector  src={VectorImage} alt={"Vector"}/>
            </Frame7>
            <Frame6 >
              <SearchByAll >
                {`Search By: All`}
                  </SearchByAll>
              <Vector1  src={Vector1Image} alt={"Vector"}/>
            </Frame6>
          </Filters>
          <Calendar  src={CalendarImage} alt={"Calendar"}/>
          <SearchBar >
            <Rectangle17155 >
            </Rectangle17155>
            <SearchWoTitle >
              {`Search WO#/Title`}
                </SearchWoTitle>
            <Group7281 >
              <Rectangle17156 >
              </Rectangle17156>
              <Vector2  src={Vector2Image} alt={"Vector"}/>
            </Group7281>
          </SearchBar>
          <ResetButton  src={ResetButtonImage} alt={"Reset Button"}/>
        </Frame2>
        <Frame1 >
          <Frame3 >
            <Frame4 >
              <Rectangle17157  src={Rectangle17157Image} alt={"Rectangle 17157"}/>
              <GroupingByMonths >
                {`Grouping by Months`}
                  </GroupingByMonths>
            </Frame4>
            <Frame5 >
              <Legend >
                {`Legend`}
                  </Legend>
              <Vector3  src={Vector3Image} alt={"Vector"}/>
            </Frame5>
          </Frame3>
        </Frame1>
      </TopFiltersAnotherOpt>
    </TarikaFilters1>
  );
}

export default TarikaFilters;
