/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import VectorImage from './assets/images/tarikafilters_Vector_5.png';
import Vector1Image from './assets/images/tarikafilters_Vector_4.png';
import Vector2Image from './assets/images/tarikafilters_Vector_3.png';
import Vector3Image from './assets/images/tarikafilters_Vector_2.png';
import Vector4Image from './assets/images/tarikafilters_Vector_1.png';
import Rectangle17157Image from './assets/images/tarikafilters_Rectangle_17157.png';
import Vector5Image from './assets/images/tarikafilters_Vector.png';
import { styled } from '@mui/material/styles';

 
const TarikaFilters1 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 38px`,  
  boxSizing: `border-box`,  
  width: "100%",  
});
  
const TopFiltersAnotherOpt = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  height: `33px`,  
  width: `1510px`,  
  margin: `0px`,  
});
  
const Filters = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `191.31px`,  
  height: `7px`,  
  left: `0px`,  
  top: `14px`,  
});
  
const Status = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `79.13px`,  
  height: `7px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector = styled("img")({  
  height: `7px`,  
  width: `10.02px`,  
  position: `absolute`,  
  left: `89px`,  
  top: `7px`,  
});
  
const StatusAll = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `61.1px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `1px`,  
});
  
const SearchBy = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `102.17px`,  
  height: `7px`,  
  left: `89px`,  
  top: `0px`,  
});
  
const Vector1 = styled("img")({  
  height: `7px`,  
  width: `10.02px`,  
  position: `absolute`,  
  left: `112px`,  
  top: `7px`,  
});
  
const SearchByAll = styled("div")({  
  textAlign: `right`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  width: `83.14px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `1px`,  
});
  
const Calendar = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `41px`,  
  height: `33px`,  
  left: `209px`,  
  top: `0px`,  
});
  
const Rectangle17155 = styled("div")({  
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `5px`,  
  width: `41px`,  
  height: `33px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector2 = styled("img")({  
  height: `19.97px`,  
  width: `17.47px`,  
  position: `absolute`,  
  left: `12px`,  
  top: `7px`,  
});
  
const Legends = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `97px`,  
  height: `33px`,  
  left: `1413px`,  
  top: `0px`,  
});
  
const Rectangle171551 = styled("div")({  
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `5px`,  
  width: `97px`,  
  height: `33px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Group7279 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `65.7px`,  
  height: `7px`,  
  left: `16px`,  
  top: `13px`,  
});
  
const Legend = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `0px`,  
  top: `2px`,  
});
  
const Vector3 = styled("img")({  
  height: `7px`,  
  width: `11.62px`,  
  position: `absolute`,  
  left: `77px`,  
  top: `7px`,  
});
  
const SearchBar = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `579px`,  
  height: `33px`,  
  left: `270px`,  
  top: `0px`,  
});
  
const Rectangle171552 = styled("div")({  
  border: `0.5px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `5px`,  
  width: `579px`,  
  height: `33px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const SearchWoTitle = styled("div")({  
  textAlign: `right`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(112, 112, 112, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `12px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `20px`,  
  top: `17px`,  
});
  
const Group7281 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `23px`,  
  height: `23px`,  
  left: `547px`,  
  top: `6px`,  
});
  
const Rectangle17156 = styled("div")({  
  backgroundColor: `rgba(53, 53, 53, 1)`,  
  borderRadius: `3px`,  
  width: `23px`,  
  height: `23px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Vector4 = styled("img")({  
  height: `12.52px`,  
  width: `12.52px`,  
  position: `absolute`,  
  left: `5px`,  
  top: `5px`,  
});
  
const GroupingByMonths = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `154px`,  
  height: `19px`,  
  left: `1239px`,  
  top: `9px`,  
});
  
const Rectangle17157 = styled("img")({  
  height: `16px`,  
  width: `16px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `3px`,  
});
  
const GroupingByMonths1 = styled("div")({  
  textAlign: `right`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Segoe UI`,  
  fontWeight: `400`,  
  fontSize: `14px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `25px`,  
  top: `0px`,  
});
  
const ResetButton = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `41px`,  
  height: `33px`,  
  left: `869px`,  
  top: `0px`,  
});
  
const Calendar1 = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `41px`,  
  height: `33px`,  
  left: `0px`,  
  top: `0px`,  
});
  
const Rectangle171553 = styled("div")({  
  border: `0.5px solid rgba(0, 0, 0, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `5px`,  
  width: `41px`,  
  height: `33px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
  
const IconAlternateRedo = styled("div")({  
  display: `flex`,  
  position: `absolute`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `17.1px`,  
  height: `17.1px`,  
  left: `12px`,  
  top: `8px`,  
});
  
const Vector5 = styled("img")({  
  height: `17.1px`,  
  width: `17.1px`,  
  position: `absolute`,  
  left: `0px`,  
  top: `0px`,  
});
 
function TarikaFilters(props) {
  return (
    <TarikaFilters1 className={props.className} >
      <TopFiltersAnotherOpt >
        <Filters >
          <Status >
            <Vector  src={VectorImage} alt={"Vector"}/>
            <StatusAll >
              {`Status: All`}
                </StatusAll>
          </Status>
          <SearchBy >
            <Vector1  src={Vector1Image} alt={"Vector"}/>
            <SearchByAll >
              {`Search By: All`}
                </SearchByAll>
          </SearchBy>
        </Filters>
        <Calendar >
          <Rectangle17155 >
          </Rectangle17155>
          <Vector2  src={Vector2Image} alt={"Vector"}/>
        </Calendar>
        <Legends >
          <Rectangle171551 >
          </Rectangle171551>
          <Group7279 >
            <Legend >
              {`Legend`}
                </Legend>
            <Vector3  src={Vector3Image} alt={"Vector"}/>
          </Group7279>
        </Legends>
        <SearchBar >
          <Rectangle171552 >
          </Rectangle171552>
          <SearchWoTitle >
            {`Search WO#/Title`}
              </SearchWoTitle>
          <Group7281 >
            <Rectangle17156 >
            </Rectangle17156>
            <Vector4  src={Vector4Image} alt={"Vector"}/>
          </Group7281>
        </SearchBar>
        <GroupingByMonths >
          <Rectangle17157  src={Rectangle17157Image} alt={"Rectangle 17157"}/>
          <GroupingByMonths1 >
            {`Grouping by Months`}
              </GroupingByMonths1>
        </GroupingByMonths>
        <ResetButton >
          <Calendar1 >
            <Rectangle171553 >
            </Rectangle171553>
          </Calendar1>
          <IconAlternateRedo >
            <Vector5  src={Vector5Image} alt={"Vector"}/>
          </IconAlternateRedo>
        </ResetButton>
      </TopFiltersAnotherOpt>
    </TarikaFilters1>
  );
}

export default TarikaFilters;
