/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { styled } from '@mui/material/styles'
import RenderTable from './RenderTable'

const TarikaCenterList1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: '100%',
})
const TarikaTable = styled('table')({
  margin: `16px`,
  border: `2px solid forestgreen`,
  width: `1440px`,
  height: `200px`,
})

const TarikaTableData = styled('td')({
  textAlign: 'center',
  padding: '5px 10px',
})
const TarikaTableRow = styled('tr')({
  borderBottom: `1px solid black`,
})
const LoadingBanner = styled('div')({
  textAlign: 'center',
  width: '100%',
})

function TarikaCenterList(props) {
  if (props.data.loading) {
    return (
      <LoadingBanner>
        <h2>Loading...</h2>
      </LoadingBanner>
    )
  }
  return (
    <TarikaCenterList1 className={props.className}>
      <RenderTable data={props.data} />
    </TarikaCenterList1>
  )
}

export default TarikaCenterList
