/**********************************************************************
 *
 *   Component hook generated by Quest
 *
 *   Code Logic for the component goes in this hook
 *   To setup bindings that use the data here or call the functions here, use the Quest editor
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { useNavigate, useLocation } from 'react-router-dom'

const useTarikaSideBar = () => {
  const location = useLocation()
  const navigate = useNavigate()
  let data = {}
  const handleNavigation = (path) => {
    console.log('location.location', location)
    navigate(path, { replace: true })
  }

  let fns = { handleNavigation }
  return { data, fns }
}

export default useTarikaSideBar
