/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import MainBgImage from './assets/images/LoginScreen_Main_BG_1.png'
import WhitePatternImage from './assets/images/LoginScreen_White_Pattern_1.png'
import Ebims1Image from './assets/images/LoginScreen_Ebims_1_1.png'
import VectorImage from './assets/images/LoginScreen_Vector_11.png'
import Vector1Image from './assets/images/LoginScreen_Vector_10.png'
import Vector2Image from './assets/images/LoginScreen_Vector_9.png'
import Vector3Image from './assets/images/LoginScreen_Vector_8.png'
import Rectangle2Image from './assets/images/LoginScreen_Rectangle_2_1.png'
import Path2264Image from './assets/images/LoginScreen_Path_2264_1.png'
import Rectangle16997Image from './assets/images/LoginScreen_Rectangle_16997_1.png'
import Vector4Image from './assets/images/LoginScreen_Vector_7.png'
import Vector5Image from './assets/images/LoginScreen_Vector_6.png'
import { styled } from '@mui/material/styles'
import useLoginScreen from './useLoginScreen'

const LoginScreen1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: `1746px`,
  height: `1033px`,
  justifyContent: `flex-start`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
})

const Frame13 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1146px`,
  height: `1047px`,
  margin: `0px`,
})

const LeftSide = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `1244.11px`,
  height: `1047px`,
  left: `0px`,
  top: `0px`,
})

const MainBg = styled('img')({
  height: `1047px`,
  width: `1244.11px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Frame12 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  left: `79px`,
  top: `364px`,
})

const LeftSideText = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `361px`,
  width: `1136.54px`,
  margin: `0px`,
})

const EnterpriseBusinessInSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const EnterpriseBusinessInSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(35, 233, 157, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const EnterpriseBusinessIn = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `1136.54px`,
  height: `145.13px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const AnEffectiveAllInOneSSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const AnEffectiveAllInOneSSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(35, 233, 157, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const AnEffectiveAllInOneS = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `1119.74px`,
  height: `70.75px`,
  position: `absolute`,
  left: `0px`,
  top: `290px`,
})

const Frame14 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `600px`,
  height: `1080px`,
  margin: `0px`,
})

const RightSide = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `600px`,
  height: `1080px`,
  left: `0px`,
  top: `0px`,
})

const WhitePattern = styled('img')({
  height: `1080px`,
  width: `600px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const EbimsLogo = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `250.9px`,
  height: `187.35px`,
  left: `187px`,
  top: `85px`,
})

const Ebims1 = styled('img')({
  height: `136.25px`,
  width: `250.9px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Group4902 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `100.99px`,
  height: `22.04px`,
  left: `75px`,
  top: `165px`,
})

const VersionV20 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `69.75px`,
  position: `absolute`,
  left: `16px`,
  top: `22px`,
})

const ClientPortal = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `100.99px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Form = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `547.62px`,
  height: `406.75px`,
  left: `39px`,
  top: `387px`,
})

const Group4905 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `547.62px`,
  height: `243.45px`,
  left: `0px`,
  top: `0px`,
})

const ClientCode = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `547.62px`,
  height: `40.07px`,
  left: `0px`,
  top: `0px`,
})

const ClientCode1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `96.82px`,
  position: `absolute`,
  left: `50px`,
  top: `11px`,
})

const Line57 = styled('div')({
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,
  width: `547.62px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `40px`,
})

const Group4904 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24.83px`,
  height: `24.04px`,
  left: `6px`,
  top: `0px`,
})

const Vector = styled('img')({
  height: `19.24px`,
  width: `19.86px`,
  position: `absolute`,
  left: `5px`,
  top: `0px`,
})

const Vector1 = styled('img')({
  height: `16.83px`,
  width: `17.38px`,
  position: `absolute`,
  left: `0px`,
  top: `7px`,
})

const UserName = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `547.62px`,
  height: `41.08px`,
  left: `0px`,
  top: `102px`,
})

const Group4903 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `127.68px`,
  height: `24.04px`,
  left: `6px`,
  top: `0px`,
})

const Username = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `83.29px`,
  position: `absolute`,
  left: `44px`,
  top: `12px`,
})

const Vector2 = styled('img')({
  height: `24.04px`,
  width: `24.83px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Line571 = styled('div')({
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,
  width: `547.62px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `41px`,
})

const Password = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `547.62px`,
  height: `40.07px`,
  left: `0px`,
  top: `203px`,
})

const Group49031 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `124.93px`,
  height: `22.04px`,
  left: `3px`,
  top: `0px`,
})

const FluentKey24Filled = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22.9px`,
  height: `22.04px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
})

const Vector3 = styled('img')({
  height: `21.71px`,
  width: `22.67px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Password1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `78.08px`,
  position: `absolute`,
  left: `47px`,
  top: `11px`,
})

const Line572 = styled('div')({
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,
  width: `547.62px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `40px`,
})

const AdditinalOptions = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `544.1px`,
  height: `39.07px`,
  left: `4px`,
  top: `284px`,
})

const ForgotPasswordSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const ForgotPasswordSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const ForgotPassword = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `124.88px`,
  height: `19.04px`,
  position: `absolute`,
  left: `419px`,
  top: `11px`,
})

const KeepMeLoggedIn = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `192.15px`,
  height: `39.07px`,
  left: `0px`,
  top: `0px`,
})

const KeepMeLoggedIn1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `133.8px`,
  height: `19.04px`,
  position: `absolute`,
  left: `58px`,
  top: `11px`,
})

const Check = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `43.46px`,
  height: `39.07px`,
  left: `0px`,
  top: `0px`,
})

const Rectangle2 = styled('img')({
  height: `39.07px`,
  width: `43.46px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Path2264 = styled('img')({
  height: `15.34px`,
  width: `22.4px`,
  position: `absolute`,
  left: `10px`,
  top: `12px`,
})

const LoginButton = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `156.16px`,
  height: `44.08px`,
  left: `0px`,
  top: `363px`,
  cursor: `pointer`,
})

const Rectangle16997 = styled('img')({
  height: `44.08px`,
  width: `156.16px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
  cursor: `pointer`,
})

const Login = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(249, 249, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `54.82px`,
  height: `24.04px`,
  position: `absolute`,
  left: `24px`,
  top: `10px`,
})

const Vector4 = styled('img')({
  height: `25.05px`,
  width: `25.8px`,
  position: `absolute`,
  left: `94px`,
  top: `10px`,
})

const Email = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `196.55px`,
  height: `12.02px`,
  left: `216px`,
  top: `1037px`,
})

const SupportTarikagroupCo = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(11, 87, 245, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `168.61px`,
  position: `absolute`,
  left: `28px`,
  top: `4px`,
})

const Vector5 = styled('img')({
  height: `12.02px`,
  width: `17.6px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

function LoginScreen(props) {
  const { fns } = useLoginScreen()
  return (
    <LoginScreen1 className={props.className}>
      <Frame13>
        <LeftSide>
          <MainBg src={MainBgImage} alt={'Main BG'} />
          <Frame12>
            <LeftSideText>
              <EnterpriseBusinessIn>
                <EnterpriseBusinessInSpan1>{`Enterprise Business Information 
`}</EnterpriseBusinessInSpan1>
                <EnterpriseBusinessInSpan2>{`Management System`}</EnterpriseBusinessInSpan2>
              </EnterpriseBusinessIn>
              <AnEffectiveAllInOneS>
                <AnEffectiveAllInOneSSpan1>{`An effective all-in-one solution for your entire business that streamlines the processes and saves time.
For more information `}</AnEffectiveAllInOneSSpan1>
                <AnEffectiveAllInOneSSpan2>{`click here`}</AnEffectiveAllInOneSSpan2>
              </AnEffectiveAllInOneS>
            </LeftSideText>
          </Frame12>
        </LeftSide>
      </Frame13>
      <Frame14>
        <RightSide>
          <WhitePattern src={WhitePatternImage} alt={'White Pattern'} />
          <EbimsLogo>
            <Ebims1 src={Ebims1Image} alt={'Ebims 1'} />
            <Group4902>
              <VersionV20>{`Version: v2.0`}</VersionV20>
              <ClientPortal>{`Client Portal`}</ClientPortal>
            </Group4902>
          </EbimsLogo>
          <Form>
            <Group4905>
              <ClientCode>
                <ClientCode1>{`Client Code`}</ClientCode1>
                <Line57></Line57>
                <Group4904>
                  <Vector src={VectorImage} alt={'Vector'} />
                  <Vector1 src={Vector1Image} alt={'Vector'} />
                </Group4904>
              </ClientCode>
              <UserName>
                <Group4903>
                  <Username>{`Username`}</Username>
                  <Vector2 src={Vector2Image} alt={'Vector'} />
                </Group4903>
                <Line571></Line571>
              </UserName>
              <Password>
                <Group49031>
                  <FluentKey24Filled>
                    <Vector3 src={Vector3Image} alt={'Vector'} />
                  </FluentKey24Filled>
                  <Password1>{`Password`}</Password1>
                </Group49031>
                <Line572></Line572>
              </Password>
            </Group4905>
            <AdditinalOptions>
              <ForgotPassword>
                <ForgotPasswordSpan1>{`Forgot `}</ForgotPasswordSpan1>
                <ForgotPasswordSpan2>{`password?`}</ForgotPasswordSpan2>
              </ForgotPassword>
              <KeepMeLoggedIn>
                <KeepMeLoggedIn1>{`Keep me logged in`}</KeepMeLoggedIn1>
                <Check>
                  <Rectangle2 src={Rectangle2Image} alt={'Rectangle 2'} />
                  <Path2264 src={Path2264Image} alt={'Path 2264'} />
                </Check>
              </KeepMeLoggedIn>
            </AdditinalOptions>
            <LoginButton onClick={() => fns.handleLogin('/workorders')}>
              <Rectangle16997
                onClick={() => fns.handleLogin('/workorders')}
                src={Rectangle16997Image}
                alt={'Rectangle 16997'}
              />
              <Login>{`LOGIN`}</Login>
              <Vector4 src={Vector4Image} alt={'Vector'} />
            </LoginButton>
          </Form>
          <Email>
            <SupportTarikagroupCo>
              {`support@tarikagroup.com`}
            </SupportTarikagroupCo>
            <Vector5 src={Vector5Image} alt={'Vector'} />
          </Email>
        </RightSide>
      </Frame14>
    </LoginScreen1>
  )
}

export default LoginScreen
