/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import BgImage1Image from './assets/images/LoginScreen_BG_Image_1.png'
import WhitePatternImage from './assets/images/LoginScreen_White_Pattern.png'
import Ebims1Image from './assets/images/LoginScreen_Ebims_1.png'
import VectorImage from './assets/images/LoginScreen_Vector_6.png'
import Vector1Image from './assets/images/LoginScreen_Vector_5.png'
import Vector2Image from './assets/images/LoginScreen_Vector_4.png'
import Vector3Image from './assets/images/LoginScreen_Vector_3.png'
import Rectangle2Image from './assets/images/LoginScreen_Rectangle_2.png'
import Path2264Image from './assets/images/LoginScreen_Path_2264.png'
import Rectangle16997Image from './assets/images/LoginScreen_Rectangle_16997.png'
import Vector4Image from './assets/images/LoginScreen_Vector_2.png'
import Vector5Image from './assets/images/LoginScreen_Vector_1.png'
import Vector6Image from './assets/images/LoginScreen_Vector.png'
import { styled } from '@mui/material/styles'
import UpperBgImage1Image from './assets/images/LoginScreen_Upper_BG_Image_1.png'
import useLoginScreen from './useLoginScreen'

const LoginScreen1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: `1080px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
})

const LeftSide = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `2470px`,
  height: `1418px`,
  left: `-550px`,
  top: `-137px`,
})

const MainBg = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `2470px`,
  height: `1418px`,
  left: `0px`,
  top: `0px`,
})

const UpperBgImage1 = styled('div')({
  backgroundImage: `url(${UpperBgImage1Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  mixBlendMode: `darken`,
  width: `2328px`,
  height: `1418px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const BgImage1 = styled('img')({
  height: `1080px`,
  width: `1920px`,
  position: `absolute`,
  left: `550px`,
  top: `137px`,
})

const LeftSideText = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `947px`,
  height: `199px`,
  left: `736px`,
  top: `577px`,
})

const EnterpriseBusinessInSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const EnterpriseBusinessInSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(35, 233, 157, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const EnterpriseBusinessIn = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `70px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const AnEffectiveAllInOneSSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const AnEffectiveAllInOneSSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(35, 233, 157, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const AnEffectiveAllInOneS = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Rajdhani`,
  fontWeight: `700`,
  fontSize: `22px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `160px`,
})

const RightSide = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `600px`,
  height: `1080px`,
  left: `1320px`,
  top: `0px`,
})

const WhitePattern = styled('img')({
  height: `1080px`,
  width: `600px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const EbimsLogo = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `241px`,
  height: `187px`,
  left: `180px`,
  top: `85px`,
})

const Ebims1 = styled('img')({
  height: `136px`,
  width: `241px`,
  objectFit: `cover`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Group4902 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `97px`,
  height: `22px`,
  left: `72px`,
  top: `165px`,
})

const VersionV20 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `15px`,
  top: `22px`,
})

const ClientPortal = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Form = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `526px`,
  height: `406px`,
  left: `37px`,
  top: `386px`,
})

const Group4905 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `526px`,
  height: `243px`,
  left: `0px`,
  top: `0px`,
})

const ClientCode = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `526px`,
  height: `40px`,
  left: `0px`,
  top: `0px`,
})

const ClientCode1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `48px`,
  top: `11px`,
})

const Line57 = styled('div')({
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,
  width: `526px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `40px`,
})

const Group4904 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  left: `2px`,
  top: `0px`,
})

const Vector = styled('img')({
  height: `19.2px`,
  width: `19.2px`,
  position: `absolute`,
  left: `5px`,
  top: `0px`,
})

const Vector1 = styled('img')({
  height: `16.8px`,
  width: `16.8px`,
  position: `absolute`,
  left: `0px`,
  top: `7px`,
})

const UserName = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `526px`,
  height: `41px`,
  left: `0px`,
  top: `102px`,
})

const Group4903 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `126px`,
  height: `24px`,
  left: `2px`,
  top: `0px`,
})

const Username = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `46px`,
  top: `12px`,
})

const Vector2 = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Line571 = styled('div')({
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,
  width: `526px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `41px`,
})

const Password = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `526px`,
  height: `40px`,
  left: `0px`,
  top: `203px`,
})

const Group49031 = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `120px`,
  height: `22px`,
  left: `3px`,
  top: `0px`,
})

const FluentKey24Filled = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `22px`,
  height: `22px`,
  left: `0px`,
  top: `0px`,
  overflow: `hidden`,
})

const Vector3 = styled('img')({
  height: `21.67px`,
  width: `21.77px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Password1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `45px`,
  top: `11px`,
})

const Line572 = styled('div')({
  border: `0.30000001192092896px solid rgba(0, 0, 0, 1)`,
  width: `526px`,
  height: `0px`,
  position: `absolute`,
  left: `0px`,
  top: `40px`,
})

const AdditinalOptions = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `526px`,
  height: `39px`,
  left: `0px`,
  top: `283px`,
})

const ForgotPasswordSpan1 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const ForgotPasswordSpan2 = styled('span')({
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
})

const ForgotPassword = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: 'unset',
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `120.72px`,
  position: `absolute`,
  left: `405px`,
  top: `11px`,
})

const KeepMeLoggedIn = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `185.76px`,
  height: `39px`,
  left: `0px`,
  top: `0px`,
})

const KeepMeLoggedIn1 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(47, 46, 55, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `600`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `129.34px`,
  position: `absolute`,
  left: `56px`,
  top: `11px`,
})

const Check = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `42.02px`,
  height: `39px`,
  left: `0px`,
  top: `0px`,
})

const Rectangle2 = styled('img')({
  height: `39px`,
  width: `42.02px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Path2264 = styled('img')({
  height: `15.31px`,
  width: `21.65px`,
  position: `absolute`,
  left: `9px`,
  top: `12px`,
})

const LoginButton = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `150px`,
  height: `44px`,
  left: `0px`,
  top: `362px`,
})

const Rectangle16997 = styled('img')({
  height: `44px`,
  width: `150px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
  cursor: `pointer`,
})

const Login = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(249, 249, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `18px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `20px`,
  top: `10px`,
})

const Vector4 = styled('img')({
  height: `25px`,
  width: `24.94px`,
  position: `absolute`,
  left: `88px`,
  top: `10px`,
})

const Email = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `190.01px`,
  height: `12px`,
  left: `205px`,
  top: `1035px`,
})

const SupportTarikagroupCo = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(11, 87, 245, 1)`,
  fontStyle: `normal`,
  fontFamily: `Segoe UI`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  position: `absolute`,
  left: `27px`,
  top: `4px`,
})

const Vector5 = styled('img')({
  height: `12px`,
  width: `17.01px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

const Frame = styled('div')({
  display: `flex`,
  position: `absolute`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `24px`,
  height: `24px`,
  left: `1241px`,
  top: `586px`,
  overflow: `hidden`,
})

const Vector6 = styled('img')({
  height: `24px`,
  width: `24px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
})

function LoginScreen(props) {
  const { fns } = useLoginScreen()
  return (
    <LoginScreen1 className={props.className}>
      <LeftSide>
        <MainBg>
          <UpperBgImage1></UpperBgImage1>
          <BgImage1 src={BgImage1Image} alt={'BG Image 1'} />
        </MainBg>
        <LeftSideText>
          <EnterpriseBusinessIn>
            <EnterpriseBusinessInSpan1>{`Enterprise Business Information 
`}</EnterpriseBusinessInSpan1>
            <EnterpriseBusinessInSpan2>{`Management System`}</EnterpriseBusinessInSpan2>
          </EnterpriseBusinessIn>
          <AnEffectiveAllInOneS>
            <AnEffectiveAllInOneSSpan1>{`An effective all-in-one solution for your entire business that streamlines the processes and saves time.
For more information `}</AnEffectiveAllInOneSSpan1>
            <AnEffectiveAllInOneSSpan2>{`click here`}</AnEffectiveAllInOneSSpan2>
          </AnEffectiveAllInOneS>
        </LeftSideText>
      </LeftSide>
      <RightSide>
        <WhitePattern src={WhitePatternImage} alt={'White Pattern'} />
        <EbimsLogo>
          <Ebims1 src={Ebims1Image} alt={'Ebims 1'} />
          <Group4902>
            <VersionV20>{`Version: v2.0`}</VersionV20>
            <ClientPortal>{`Client Portal`}</ClientPortal>
          </Group4902>
        </EbimsLogo>
        <Form>
          <Group4905>
            <ClientCode>
              <ClientCode1>{`Client Code`}</ClientCode1>
              <Line57></Line57>
              <Group4904>
                <Vector src={VectorImage} alt={'Vector'} />
                <Vector1 src={Vector1Image} alt={'Vector'} />
              </Group4904>
            </ClientCode>
            <UserName>
              <Group4903>
                <Username>{`Username`}</Username>
                <Vector2 src={Vector2Image} alt={'Vector'} />
              </Group4903>
              <Line571></Line571>
            </UserName>
            <Password>
              <Group49031>
                <FluentKey24Filled>
                  <Vector3 src={Vector3Image} alt={'Vector'} />
                </FluentKey24Filled>
                <Password1>{`Password`}</Password1>
              </Group49031>
              <Line572></Line572>
            </Password>
          </Group4905>
          <AdditinalOptions>
            <ForgotPassword>
              <ForgotPasswordSpan1>{`Forgot `}</ForgotPasswordSpan1>
              <ForgotPasswordSpan2>{`password?`}</ForgotPasswordSpan2>
            </ForgotPassword>
            <KeepMeLoggedIn>
              <KeepMeLoggedIn1>{`Keep me logged in`}</KeepMeLoggedIn1>
              <Check>
                <Rectangle2 src={Rectangle2Image} alt={'Rectangle 2'} />
                <Path2264 src={Path2264Image} alt={'Path 2264'} />
              </Check>
            </KeepMeLoggedIn>
          </AdditinalOptions>
          <LoginButton>
            <Rectangle16997
              onClick={() => fns.handleLogin('/workorders')}
              src={Rectangle16997Image}
              alt={'Rectangle 16997'}
            />
            <Login>{`LOGIN`}</Login>
            <Vector4 src={Vector4Image} alt={'Vector'} />
          </LoginButton>
        </Form>
        <Email>
          <SupportTarikagroupCo>
            {`support@tarikagroup.com`}
          </SupportTarikagroupCo>
          <Vector5 src={Vector5Image} alt={'Vector'} />
        </Email>
      </RightSide>
      <Frame>
        <Vector6 src={Vector6Image} alt={'Vector'} />
      </Frame>
    </LoginScreen1>
  )
}

export default LoginScreen
